name: Main CI

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/hcrevive-*.jar
